[package]
name = "goxlr-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-ipc = {path = "../ipc", features = ["clap"] }
tokio = {version = "1.0", features=["full"]}
simplelog = "0.11.1"
anyhow = "1.0"
clap = { version = "3.0.0", features = ["derive"] }

