[package]
name = "goxlr-profile-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.0"
enum-map-derive = "0.8"
thiserror = "1.0"

strum = { version = "0.23", features = ["derive"] }

ritelinked = "0.3.2"

xml-rs = "0.8"