[package]
name = "goxlr-profile-loader"
version = "0.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.1.0"
enum-map-derive = "0.8"
thiserror = "1.0"
zip = "0.5"
strum = { version = "0.23", features = ["derive"] }
ritelinked = "0.3.2"
xml-rs = "0.8"
byteorder = "1"
rand = "0.8.5"

anyhow = "1.0"
log = "0.4.14"