[package]
name = "goxlr-launcher"
version = "0.8.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
goxlr-ipc = { path = "../ipc" }
goxlr-types = { path = "../types" }

interprocess = { version = "1.2.0", features=["tokio_support"] }
tokio = { version = "1.0", features=["full"] }
sysinfo = "0.27.1"
which = "4.3.0"

[target.'cfg(target_family = "unix")'.dependencies]
fork = "0.1.20"

[target.'cfg(target_os = "windows")'.build-dependencies]
windres = "*"
