[package]
name = "goxlr-types"
version = "0.1.0"
edition = "2021"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>", "Craig McLure <craig@mclure.net>"]
description = "A helper crate for all types used in the GoXLR IPC"
repository = "https://github.com/GoXLR-on-Linux/GoXLR-Utility"
license = "MIT"
categories = ["hardware-support", "api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
strum = { version = "0.23", features = ["derive"] }
serde = { version = "1.0", features = ["derive"], optional = true}
clap = { version = "3.0.0", features = ["derive"], optional = true}
enumset = { version = "1.0.8", optional = true }

[target.'cfg(serde)'.dependencies.enumset]
version = "1.0.8"
features = ["serde"]
