[package]
name = "goxlr-initialiser"
version = "0.7.1"
edition = "2021"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>", "Craig McLure <craig@mclure.net>", "Lars Mühlbauer <lm41@dismail.de>"]
description = "Finds, checks and initialises any unconfigured GoXLR devices"
repository = "https://github.com/GoXLR-on-Linux/GoXLR-Utility"
license = "MIT"
categories = ["hardware-support", "command-line-utilities"]

[dependencies]
rusb = "0.9"
anyhow = "1.0"