[package]
name = "goxlr-defaults"
version = "0.12.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
include_dir = "0.7.3"
