[package]
name = "goxlr-daemon"
version = "0.1.0"
edition = "2021"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>", "Craig McLure <craig@mclure.net>", "Lars Mühlbauer <lm41@dismail.de>"]
description = "Allows control of a TC-Helicon GoXLR or GoXLR Mini, by maintaining an interaction with it over USB in the background."
repository = "https://github.com/GoXLR-on-Linux/GoXLR-Utility"
license = "MIT"
categories = ["hardware-support", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-usb = {path = "../usb" }
goxlr-ipc = {path = "../ipc" }
goxlr-types = {path = "../types" }
goxlr-profile-loader = {path = "../profile" }
simplelog = "0.11.1"
tokio = {version = "1.0", features=["full"]}
log = "0.4.14"
anyhow = "1.0"
strum = { version = "0.23"}
enumset = "1.0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
directories = "4.0"
byteorder = "1"
enum-map = "2.1.0"
futures = "0.3.21"

## HTTPd Server
actix = "0.13"
actix-web-actors = "4.1"
actix-web = "4.1"
actix-plus-static-files = {git = "https://github.com/john01dav/actix-plus", commit = "4f7837c0d3d413bf82d7906b33abb7801340c063"}

# Enable debugging symbols, and disable optimisation..
[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
