name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build-docs
      run: cargo doc
    - name: Setup node
      uses: actions/setup-node@v1
    - name: Upload to GitHub
      uses: LasyIsLazy/github-upload-action@v0.1.0
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        file-path: target/doc/
        owner: goxlr-on-linux
        repo: GoXLR-Utility
        remote-dir: docs/
