name: Get Current Version
on: workflow_call
jobs:
  get_version:
    name: "Get Version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Update Cargo.lock
        run: cargo update
      - name: Save Version
        run: 'echo "version=$(cargo pkgid -p goxlr-daemon | cut -d@ -f2)" >> $GITHUB_OUTPUT'
