name: Get Current Version
on: workflow_call
jobs:
  get_version:
    name: "Get Version"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: "Check out Repository"
        uses: actions/checkout@v3

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Update Cargo.lock"
        run: cargo update

      - name: "Get Version"
        run: 'echo "version=$(cargo pkgid -p goxlr-daemon | cut -d@ -f2)" >> $GITHUB_OUTPUT'
