name: Get Current Version
on: workflow_call
jobs:
  get_version:
    name: "Get Version"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.store_version.outputs.version }}
    steps:
      - name: "Check out Repository"
        uses: actions/checkout@v3

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable

      - name: "Update Cargo.lock"
        run: cargo update

      - name: "Err.."
        run: echo $GITHUB_OUTPUT

      - name: "Test Store"
        run: echo "version=$(cargo pkgid -p goxlr-daemon | cut -d@ -f2)"

      - name: "Store Version"
        id: store_version
        #run: echo "version=$(cargo pkgid -p goxlr-daemon | cut -d@ -f2)" >> "$GITHUB_OUTPUT"
        run: echo "version=0.0.0" >> $GITHUB_OUTPUT

      - name: "Check Version"
        run: cat $GITHUB_OUTPUT
