name: Create Release Draft
on: workflow_dispatch
jobs:

  # Before we do anything, run the existing test suite..
  verify:
    uses: ./.github/workflows/build.yml

  build:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-deb and cargo-generate-rpm
        run: cargo install cargo-deb cargo-generate-rpm

      - name: Build Packages
        run: ./ci/build-packages
        shell: bash

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-artifact
          path: ./target/debian/*.deb

      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpm-artifact
          path: ./target/generate-rpm/*.rpm
