name: Create Test Build
on: workflow_dispatch
jobs:

  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Update Cargo.lock
        run: cargo update
      - id: version
        run: 'echo "::set-output name=version::$(cargo pkgid -p goxlr-daemon | cut -d@ -f2)"'

  build_windows:
    runs-on: windows-latest
    needs: [get_version]
    steps:
      # Firstly Checkout our Repository..
      - uses: actions/checkout@v3
        with:
          path: goxlr-utility

      # Now Checkout the App Wrappers repository..
      - uses: actions/checkout@v3
        with:
          repository: frostycoolslug/goxlr-utility-ui
          path: goxlr-utility-ui

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Preparing Cache..
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=goxlr-utility/Cargo.toml --release --all-features

      # Build the UI into the same target directory..
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=goxlr-utility-ui/src-tauri/Cargo.toml --target-dir=goxlr-utility/target --release

      # Prepare NSIS
      - name: Build NSIS Packages
        uses: joncloud/makensis-action@publish
        with:
          script-file: goxlr-utility/ci/nsis/goxlr-utility.nsi
          arguments: "/DPRODUCT_VERSION=${{ needs.get_version.outputs.version }}"

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifact
          path: ./goxlr-utility/ci/Output/*.exe

  build:
    runs-on: ubuntu-latest
    needs: [get_version]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Required Libraries
        run: |
          sudo apt-get update
          sudo apt-get install libpulse0 libdbus-1-dev pkg-config libspeechd-dev

      - name: Install cargo-deb and cargo-generate-rpm
        run: cargo install cargo-deb cargo-generate-rpm

      - name: Preparing Cache..
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build Packages
        run: ./ci/build-packages
        shell: bash

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-artifact
          path: ./target/debian/*.deb

      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpm-artifact
          path: ./target/generate-rpm/*.rpm
